apiVersion: apps/v1
kind: Deployment
metadata:
  name: logcord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logcord
  template:
    metadata:
      labels:
        app: logcord
    spec:
      containers:
        - name: logcord
          image: ghcr.io/python-discord/logcord:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 150m
              memory: 350Mi
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: logcord-config-env
            - secretRef:
                name: logcord-secret-env
          volumeMounts:
          - mountPath: /tmp
            name: logcord-temp-vol
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
      - name: logcord-temp-vol
        emptyDir: {}
