apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: public-stats
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`stats.pythondiscord.com`)
    kind: Rule
    services:
    - name: public-stats
      port: 8000
  tls:
    certResolver: cfresolver
    domains:
    - main: "*.pythondiscord.com"
