apiVersion: apps/v1
kind: Deployment
metadata:
  name: redash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redash
  template:
    metadata:
      labels:
        app: redash
    spec:
      containers:
        - name: server
          image: redash/redash:preview
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 300Mi
          ports:
            - containerPort: 5000
          env:
            - name: REDASH_WEB_WORKERS
              value: "1"
          envFrom:
            - secretRef:
                name: redash-secrets
          args: ["server"]
        - name: scheduler
          image: redash/redash:preview
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 250Mi
          env:
            - name: WORKERS_COUNT
              value: "1"
          envFrom:
            - secretRef:
                name: redash-secrets
          args: ["scheduler"]
        - name: worker
          image: redash/redash:preview
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 200m
              memory: 400Mi
          imagePullPolicy: Always
          env:
            - name: WORKERS_COUNT
              value: "1"
          envFrom:
            - secretRef:
                name: redash-secrets
          args: ["worker"]
